---

- name: Install Cyrus SASL if enabled
  pacman:
    name: 'cyrus-sasl'
    state: 'present'

- name: Configure Cyrus SASL Authentication
  template:
    src: 'etc/postfix/sasl/smtpd.conf.j2'
    dest: '/usr/lib/sasl2/smtpd.conf'
    owner: 'root'
    group: 'postfix'
    mode: '0640'

- name: Configure saslauthd service
  template:
    src: 'etc/default/saslauthd-smtpd.j2'
    dest: '/etc/default/saslauthd'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart saslauthd' ]
  register: postfix_register_configure_saslauthd
