---

- name: Check postfix and restart
  command: /usr/sbin/postfix -c /etc/postfix check
  notify: [ 'Restart postfix' ]

- name: Restart postfix
  service:
    name: 'postfix'
    state: 'restarted'

- name: Restart saslauthd
  service:
    name: 'saslauthd'
    state: 'restarted'
