---

- name: Manage Postfix SMTP service
  hosts: [ 'debops_service_postfix' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ postfix_ferm_dependent_rules }}'

    - role: debops.postfix
      tags: [ 'role::postfix' ]

